service: my-lambda-project

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1  # Change to your desired region

functions:
  myLambdaFunction:
    handler: handler.myLambdaHandler
    events:
      - http:
          path: my-endpoint
          method: any

resources:
  Resources:
    MyS3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: my-s3-bucket

plugins:
  - serverless-iam-roles-per-function
